version: "3.3"

networks:
  # communication to web and clients
  lemmyexternalproxy:
  # communication between lemmy services
  lemmyinternal:
    internal: true

services:
  proxy:
    image: nginx:1
    networks:
      - lemmyinternal
      - lemmyexternalproxy
    ports:
      # only ports facing any connection from outside
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      # setup your certbot and letsencrypt config
      # - /services/lemmy/certbot/config:/var/www/certbot
      # - /services/lemmy/certbot/letsencrypt:/etc/letsencrypt/live
    restart: always
  #    depends_on:q
  #      - pictrs
  #      - lemmy-ui

  lemmy:
    image: dessalines/lemmy:0.19.3
    environment:
      - RUST_LOG="debug"
    networks:
      - lemmyinternal
      - lemmyexternalproxy
    volumes:
      - ./config/lemmy.hjson:/config/config.hjson
    ports:
      - "8536:8536"
    depends_on:
      - postgres
      - pictrs
    restart: always

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.3
    networks:
      - lemmyinternal
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=127.0.0.1
      - LEMMY_HTTPS=false
    ports:
      - "1234:1234"
    depends_on:
      - lemmy
    restart: always
    healthcheck:
      disable: true
      test: []

  postgres:
    image: postgres:15
    hostname: postgres
    networks:
      - lemmyinternal
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    restart: always

  pictrs:
    image: asonix/pictrs:latest
    hostname: pictrs
    networks:
      - lemmyinternal
    environment:
      - PICTRS__API_KEY=pictrskey
    user: 991:991
    restart: always
